Fallback to RubyGems 3.4.22 for Ruby 2.7
```
$ ruby -v
ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x86_64-linux]
$ gem update --system
Updating rubygems-update
ERROR:  Error installing rubygems-update:
        rubygems-update-3.5.6 requires Ruby version >= 3.0.0. The current ruby version is 2.7.8.
$
```

https://github.com/rubygems/rubygems/blob/master/CHANGELOG.md#350--2023-12-15
> Drop ruby 2.6 and 2.7 support. Pull request #7116 by deivid-rodriguez

https://github.com/rubygems/rubygems/pull/7116