Except `table_name` from column objects
Follow up https://github.com/rails/rails/pull/35890.

This PR fixes the following error.

```consle
% cd path/to/oracle-enhanced
% bundle exec rake

(snip)

Failures:

  1) OracleEnhancedAdapter schema dump virtual columns should dump
  correctly
     Failure/Error: expect(output).to match(/t\.virtual
  "full_name",(\s*)type: :string,(\s*)limit: 512,(\s*)as:
  "\\"FIRST_NAME\\"\|\|', '\|\|\\"LAST_NAME\\""/)

       expected "# This file is auto-generated from the current state of
       the database. Instead\n# of editing this fil...e_name' for
       #<ActiveRecord::ConnectionAdapters::OracleEnhanced::Column:0x0000000003a21bd0>\n\nend\n"
       to match /t\.virtual "full_name",(\s*)type: :string,(\s*)limit:
       512,(\s*)as: "\\"FIRST_NAME\\"\|\|', '\|\|\\"LAST_NAME\\""/
       Diff:
       @@ -1,2 +1,19 @@
       -/t\.virtual "full_name",(\s*)type: :string,(\s*)limit:
       512,(\s*)as: "\\"FIRST_NAME\\"\|\|', '\|\|\\"LAST_NAME\\""/
       +# This file is auto-generated from the current state of the
       database. Instead
       +# of editing this file, please use the migrations feature of
       Active Record to
       +# incrementally modify your database, and then regenerate this
       schema definition.
       +#
       +# This file is the source Rails uses to define your schema when
       running `rails
       +# db:schema:load`. When creating a new database, `rails
       db:schema:load` tends to
       +# be faster and is potentially less error prone than running all
       of your
       +# migrations from scratch. Old migrations may fail to apply
       correctly if those
       +# migrations use external dependencies or application code.
       +#
       +# It's strongly recommended that you check this file into your
       version control system.
       +
       +ActiveRecord::Schema.define(version: 0) do
       +
       +# Could not dump table "test_names" because of following
       NoMethodError
       +#   undefined method `table_name' for
       #<ActiveRecord::ConnectionAdapters::OracleEnhanced::Column:0x0000000003a21bd0>
       +
       +end
```