fix schema dump when oracle adapeter used on another anvironment
Without this fix schem a dump looks like:

    # Could not dump table "cms_blocks" because of following NoMethodError
    #   undefined method `column_spec_with_oracle_enhanced' for #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x0000000404c8e8>