Workaround rails/arel#491 for Oracle Database 11gR2 or lower
```ruby
 NoMethodError:
       undefined method `value_for_database' for #<Arel::Nodes::BindParam:0x000055852a3e64d0>
```

This commit will get reverted when rails/arel#491 is merged to master
or other fixes found.