Use ruby-oci8 master branch
This commit addresses these errors.

```
$ ruby active_record_gem.rb
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Using concurrent-ruby 1.1.10
Using minitest 5.15.0
Using ruby-plsql 0.8.0
Using bundler 2.4.0.dev
Fetching ruby-oci8 2.2.11
Using tzinfo 2.0.4
Using i18n 1.10.0
Using activesupport 7.1.0.alpha from https://github.com/rails/rails.git (at /home/yahonda/src/github.com/rails/rails@8ace32c)
Using activemodel 7.1.0.alpha from https://github.com/rails/rails.git (at /home/yahonda/src/github.com/rails/rails@8ace32c)
Using activerecord 7.1.0.alpha from https://github.com/rails/rails.git (at /home/yahonda/src/github.com/rails/rails@8ace32c)
Installing ruby-oci8 2.2.11 with native extensions
/home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/installer/parallel_installer.rb:220:in `handle_error': Gem::Ext::BuildError: ERROR: Failed to build gem native extension. (Bundler::InstallError)

    current directory: /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/gems/3.2.0+1/gems/ruby-oci8-2.2.11/ext/oci8
/home/yahonda/.rbenv/versions/3.2.0-dev/bin/ruby -I /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1 -r ./siteconf20220422-71557-jyrfhb.rb extconf.rb
attempting to locate oracle-instantclient...
checking load library path...
  LD_LIBRARY_PATH...
    checking /usr/lib/oracle/21/client64/lib... yes
  /usr/lib/oracle/21/client64/lib/libclntsh.so.21.1 looks like an instant client.
checking for cc... ok
checking for gcc... yes
checking for LP64... yes
checking for sys/types.h... yes
checking for ruby header... ok
checking for OCIEnvCreate() in oci.h... yes
checking for OCI_MAJOR_VERSION in oci.h... 21
checking for OCI_MINOR_VERSION in oci.h... 6
checking for localtime_r()... yes
checking for dladdr()... yes
checking for dlmodinfo()... no
checking for dlgetname()... no
checking for ruby/thread.h... yes
checking for rb_class_superclass() in ruby.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_sym2str() in ruby.h... yes
checking for plthook... plthook_elf.c
creating extconf.h
creating Makefile

current directory: /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/gems/3.2.0+1/gems/ruby-oci8-2.2.11/ext/oci8
make DESTDIR\= clean

current directory: /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/gems/3.2.0+1/gems/ruby-oci8-2.2.11/ext/oci8
make DESTDIR\=
compiling oci8lib.c
In file included from oci8lib.c:6:
oci8.h: In function ‘oci8_get_errhp’:
oci8.h:385:25: warning: old-style function definition [-Wold-style-definition]
  385 | static inline OCIError *oci8_get_errhp()
      |                         ^~~~~~~~~~~~~~
In file included from /home/yahonda/.rbenv/versions/3.2.0-dev/include/ruby-3.2.0+1/ruby/internal/config.h:25,
                 from /home/yahonda/.rbenv/versions/3.2.0-dev/include/ruby-3.2.0+1/ruby/ruby.h:15,
                 from /home/yahonda/.rbenv/versions/3.2.0-dev/include/ruby-3.2.0+1/ruby.h:38,
                 from oci8.h:10,
                 from oci8lib.c:6:
oci8lib.c: In function ‘Init_oci8lib_320’:
./extconf.h:13:22: warning: old-style function definition [-Wold-style-definition]
   13 | #define Init_oci8lib Init_oci8lib_320
      |                      ^~~~~~~~~~~~~~~~
oci8lib.c:194:1: note: in expansion of macro ‘Init_oci8lib’
  194 | Init_oci8lib()
      | ^~~~~~~~~~~~
oci8lib.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may have been intended to silence earlier diagnostics
compiling env.c
In file included from env.c:7:
oci8.h: In function ‘oci8_get_errhp’:
oci8.h:385:25: warning: old-style function definition [-Wold-style-definition]
  385 | static inline OCIError *oci8_get_errhp()
      |                         ^~~~~~~~~~~~~~
env.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may have been intended to silence earlier diagnostics
compiling error.c
In file included from error.c:8:
oci8.h: In function ‘oci8_get_errhp’:
oci8.h:385:25: warning: old-style function definition [-Wold-style-definition]
  385 | static inline OCIError *oci8_get_errhp()
      |                         ^~~~~~~~~~~~~~
error.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may have been intended to silence earlier diagnostics
compiling oci8.c
In file included from oci8.c:8:
oci8.h: In function ‘oci8_get_errhp’:
oci8.h:385:25: warning: old-style function definition [-Wold-style-definition]
  385 | static inline OCIError *oci8_get_errhp()
      |                         ^~~~~~~~~~~~~~
oci8.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may have been intended to silence earlier diagnostics
compiling ocihandle.c
In file included from ocihandle.c:10:
oci8.h: In function ‘oci8_get_errhp’:
oci8.h:385:25: warning: old-style function definition [-Wold-style-definition]
  385 | static inline OCIError *oci8_get_errhp()
      |                         ^~~~~~~~~~~~~~
ocihandle.c: In function ‘attr_get_common’:
ocihandle.c:220:16: error: implicit declaration of function ‘rb_tainted_str_new’; did you mean ‘rb_enc_str_new’? [-Werror=implicit-function-declaration]
  220 |         return rb_tainted_str_new(v.charptr, size);
      |                ^~~~~~~~~~~~~~~~~~
      |                rb_enc_str_new
ocihandle.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may have been intended to silence earlier diagnostics
cc1: some warnings being treated as errors
make: *** [Makefile:246: ocihandle.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/gems/3.2.0+1/gems/ruby-oci8-2.2.11 for inspection.
Results logged to /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/gems/3.2.0+1/extensions/x86_64-linux/3.2.0+1-static/ruby-oci8-2.2.11/gem_make.out

  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/rubygems/ext/builder.rb:95:in `run'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/rubygems/ext/builder.rb:44:in `block in make'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/rubygems/ext/builder.rb:36:in `each'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/rubygems/ext/builder.rb:36:in `make'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/rubygems/ext/ext_conf_builder.rb:63:in `block in build'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/tempfile.rb:317:in `open'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/rubygems/ext/builder.rb:161:in `build_extension'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/rubygems/ext/builder.rb:195:in `block in build_extensions'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/rubygems/ext/builder.rb:192:in `each'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/rubygems/ext/builder.rb:192:in `build_extensions'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/rubygems/installer.rb:851:in `build_extensions'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/rubygems_gem_installer.rb:28:in `install'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/source/rubygems.rb:204:in `install'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/installer/gem_installer.rb:54:in `install'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/installer/parallel_installer.rb:186:in `do_install'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/worker.rb:62:in `apply_func'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/worker.rb:57:in `block in process_queue'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/worker.rb:54:in `loop'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/worker.rb:54:in `process_queue'
  /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing ruby-oci8 (2.2.11), and Bundler cannot continue.

In Gemfile:
  activerecord-oracle_enhanced-adapter was resolved to 7.1.0.alpha, which depends on
    ruby-oci8

	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/installer/parallel_installer.rb:102:in `call'
	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/installer/parallel_installer.rb:71:in `call'
	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/installer.rb:259:in `install_in_parallel'
	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/installer.rb:209:in `install'
	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/installer.rb:89:in `block in run'
	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/process_lock.rb:12:in `block in lock'
	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/process_lock.rb:9:in `open'
	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/process_lock.rb:9:in `lock'
	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/installer.rb:71:in `run'
	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/installer.rb:23:in `install'
	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/inline.rb:63:in `block (2 levels) in gemfile'
	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/settings.rb:131:in `temporary'
	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/inline.rb:62:in `block in gemfile'
	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/settings.rb:131:in `temporary'
	from /home/yahonda/.rbenv/versions/3.2.0-dev/lib/ruby/3.2.0+1/bundler/inline.rb:55:in `gemfile'
	from active_record_gem.rb:5:in `<main>'
$
```