Address `ActiveRecord::StatementInvalid: OCIError: ORA-02289` at `structure_load`
```sql
     ActiveRecord::StatementInvalid:
       OCIError: ORA-02289: sequence does not exist: CREATE TABLE "POSTS" (
        "ID" NUMBER(38,0) DEFAULT "ORACLE_ENHANCED"."ISEQ$$_218684".nextval NOT NULL,
        "NAME" VARCHAR2(255) NOT NULL,
        "IS_DEFAULT" VARCHAR2(1) DEFAULT 'N',
        CONST
```

This implementation addresses this error but it needs to generate
`GENERATED BY DEFAULT AS IDENTITY` as follows:

* Expected SQL statement
```sql
CREATE TABLE "TEST_POSTS" ("ID" NUMBER(38) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "NAME" VARCHAR2(20))
```

* Current SQL statement with this pull request
```
CREATE TABLE "TEST_POSTS" ("ID" NUMBER(38,0) NOT NULL,  "NAME" VARCHAR2(20), CONSTRAINT SYS_C0087720 PRIMARY KEY (ID))
```