Skip RuboCop 1.84.0 to workaround `undefined method 'begin_type?' for nil`
- To workaround these errors:
```ruby
$ bundle exec rubocop
An error occurred while Layout/IndentationWidth cop was inspecting /home/yahonda/src/github.com/rsim/oracle-enhanced/guides/bug_report_templates/active_record_gem.rb:46:2.
To see the complete backtrace run rubocop -d.
An error occurred while Layout/IndentationWidth cop was inspecting /home/yahonda/src/github.com/rsim/oracle-enhanced/guides/bug_report_templates/active_record_gem_spec.rb:46:6.
To see the complete backtrace run rubocop -d.
An error occurred while Layout/IndentationWidth cop was inspecting /home/yahonda/src/github.com/rsim/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb:20:6.
To see the complete backtrace run rubocop -d.
Inspecting 73 files
...An error occurred while Layout/IndentationWidth cop was inspecting /home/yahonda/src/github.com/rsim/oracle-enhanced/guides/bug_report_templates/active_record_gem.rb:46:2.
To see the complete backtrace run rubocop -d.
.An error occurred while Layout/IndentationWidth cop was inspecting /home/yahonda/src/github.com/rsim/oracle-enhanced/guides/bug_report_templates/active_record_gem_spec.rb:46:6.
To see the complete backtrace run rubocop -d.
.................................................An error occurred while Layout/IndentationWidth cop was inspecting /home/yahonda/src/github.com/rsim/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb:20:6.
To see the complete backtrace run rubocop -d.
....................

73 files inspected, no offenses detected

3 errors occurred:
An error occurred while Layout/IndentationWidth cop was inspecting /home/yahonda/src/github.com/rsim/oracle-enhanced/guides/bug_report_templates/active_record_gem.rb:46:2.
An error occurred while Layout/IndentationWidth cop was inspecting /home/yahonda/src/github.com/rsim/oracle-enhanced/guides/bug_report_templates/active_record_gem_spec.rb:46:6.
An error occurred while Layout/IndentationWidth cop was inspecting /home/yahonda/src/github.com/rsim/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced/structure_dump_spec.rb:20:6.
Errors are usually caused by RuboCop bugs.
Please, update to the latest RuboCop version if not already in use, and report a bug if the issue still occurs on this version.
https://github.com/rubocop/rubocop/issues

Mention the following information in the issue report:
1.84.0 (using Parser 3.3.10.1, rubocop-ast 1.49.0, analyzing as Ruby 3.1, running on ruby 4.0.1) [x86_64-linux]
$
```

It will be addressed once https://github.com/rubocop/rubocop/pull/14803
is released.