Bump RuboCop version to 0.71
https://github.com/rubocop-hq/rubocop/releases/tag/v0.71.0

Additional changes made:

* Install `rubocop-rails` gem because Rails cops will be removed from RuboCop 0.72

* Rename `Layout/FirstParameterIndentation` to `Layout/IndentFirstArgument` to support RuboCop 0.68.0

```ruby
$ bundle exec rubocop
Error: The `Layout/FirstParameterIndentation` cop has been renamed to `Layout/IndentFirstArgument`.
(obsolete configuration found in .rubocop.yml, please update it)
$
```

* Use `rubocop-0-71` channel at Code Climate

Refer https://github.com/codeclimate/codeclimate/releases/tag/v0.85.3