Fallback to bundler 1.7.3 if bundler 2 is not available
https://travis-ci.org/rsim/oracle-enhanced/jobs/484610915

```ruby
$ gem install bundler
ERROR:  Error installing bundler:
	bundler requires Ruby version >= 2.3.0.
The command "gem install bundler" failed and exited with 1 during .
```